### Chronic Kidney Disease Dataset Documentation

<b>Overview</b>

This dataset was collected over approximately 2 months from a hospital in 2015. It contains medical records that can be used to predict chronic kidney disease (CKD).
Dataset Characteristics

<b>Feature Categories</b>

Numerical Features (11)

* Age (years)
* Blood Pressure (mm/Hg)
* Blood Glucose Random (mgs/dl)
* Blood Urea (mgs/dl)
* Serum Creatinine (mgs/dl)
* Sodium (mEq/L)
* Potassium (mEq/L)
* Hemoglobin (gms)
* Packed Cell Volume
* White Blood Cell Count (cells/cumm)
* Red Blood Cell Count (millions/cmm)

<b>Categorical Features (14)</b>

* Specific Gravity (values: 1.005, 1.010, 1.015, 1.020, 1.025)
* Albumin (values: 0-5)
* Sugar (values: 0-5)
* Red Blood Cells (normal, abnormal)
* Pus Cell (normal, abnormal)
* Pus Cell Clumps (present, notpresent)
* Bacteria (present, notpresent)
* Hypertension (yes, no)
* Diabetes Mellitus (yes, no)
* Coronary Artery Disease (yes, no)
* Appetite (good, poor)
* Pedal Edema (yes, no)
* Anemia (yes, no)
* Class (ckd, notckd) - Target Variable

<b>Data Source</b>

The dataset is available through the UCI Machine Learning Repository, contributed in July 2015. Original source: https://archive.ics.uci.edu/dataset/336/chronic+kidney+disease

<b>Data Quality Notes</b>

- The dataset contains missing values across various features
- Both continuous and categorical variables are present
- Medical measurements are provided in standard clinical units
- Features cover a comprehensive range of medical indicators relevant to kidney function

In [2]:
import pandas as pd

# reading the data
features = pd.read_csv('../data/chronic_kidney_disease.csv')
target = pd.read_csv('../data/chronic_kidney_disease_target.csv')

# I will merge the two dataframes
data = pd.concat([features, target], axis=1)
data.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane,class
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44.0,7800.0,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38.0,6000.0,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31.0,7500.0,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32.0,6700.0,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35.0,7300.0,4.6,no,no,no,good,no,no,ckd

In [4]:
# Lets run some diagnostics
print(data.info())
print(data.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     391 non-null    float64
 1   bp      388 non-null    float64
 2   sg      353 non-null    float64
 3   al      354 non-null    float64
 4   su      351 non-null    float64
 5   rbc     248 non-null    object
 6   pc      335 non-null    object
 7   pcc     396 non-null    object
 8   ba      396 non-null    object
 9   bgr     356 non-null    float64
 10  bu      381 non-null    float64
 11  sc      383 non-null    float64
 12  sod     313 non-null    float64
 13  pot     312 non-null    float64
 14  hemo    348 non-null    float64
 15  pcv     329 non-null    float64
 16  wbcc    294 non-null    float64
 17  rbcc    269 non-null    float64
 18  htn     398 non-null    object
 19  dm      398 non-null    object
 20  cad     398 non-null    object
 21  appet   399 non-null    object
 22  pe      399 non-null    object
 23  ane     399 non-null    object
 24  class   400 non-null    object
dtypes: float64(14), object(11)
memory usage: 78.2+ KB
None
              age          bp          sg          al          su         bgr  \
count  391.000000  388.000000  353.000000  354.000000  351.000000  356.000000
mean    51.483376   76.469072    1.017408    1.016949    0.450142  148.036517
std     17.169714   13.683637    0.005717    1.352679    1.099191   79.281714
min      2.000000   50.000000    1.005000    0.000000    0.000000   22.000000
25%     42.000000   70.000000    1.010000    0.000000    0.000000   99.000000
50%     55.000000   80.000000    1.020000    0.000000    0.000000  121.000000
75%     64.500000   80.000000    1.020000    2.000000    0.000000  163.000000
max     90.000000  180.000000    1.025000    5.000000    5.000000  490.000000

               bu          sc         sod         pot        hemo         pcv  \
count  381.000000  383.000000  313.000000  312.000000  348.000000  329.000000
mean    57.425722    3.072454  137.528754    4.627244   12.526437   38.884498
std     50.503006    5.741126   10.408752    3.193904    2.912587    8.990105
min      1.500000    0.400000    4.500000    2.500000    3.100000    9.000000
25%     27.000000    0.900000  135.000000    3.800000   10.300000   32.000000
50%     42.000000    1.300000  138.000000    4.400000   12.650000   40.000000
75%     66.000000    2.800000  142.000000    4.900000   15.000000   45.000000
max    391.000000   76.000000  163.000000   47.000000   17.800000   54.000000

               wbcc        rbcc
count    294.000000  269.000000
mean    8406.122449    4.707435
std     2944.474190    1.025323
min     2200.000000    2.100000
25%     6500.000000    3.900000
50%     8000.000000    4.800000
75%     9800.000000    5.400000
max    26400.000000    8.000000

In [3]:
# Lets do some preprocessing
# Checking missing values

missing_values = data.isnull().sum()
missing_values = missing_values[missing_values > 0]
print(missing_values)

age        9
bp        12
sg        47
al        46
su        49
rbc      152
pc        65
pcc        4
ba         4
bgr       44
bu        19
sc        17
sod       87
pot       88
hemo      52
pcv       71
wbcc     106
rbcc     131
htn        2
dm         2
cad        2
appet      1
pe         1
ane        1
dtype: int64